
# This GitHub Action automates the process of building Grafana plugins.
# (For more information, see https://github.com/grafana/plugin-actions/blob/main/build-plugin/README.md)
name: Test Actions

on:
  workflow_dispatch:
    inputs:
      use-input:
        description: "Use input"
        required: true
        default: false
        type: boolean
      string-input:
        description: "String input"
        required: true
        default: "MONKEY"
        type: string

permissions: read-all

jobs:
  test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: |
          echo "use-input: ${{ inputs.use-input }}"
          echo "string-input: ${{ inputs.string-input }}"
          echo "use-input && string-input: ${{ inputs.use-input && inputs.string-input }}"
  another-test:
    name: Another test
    uses: ./.github/workflows/dummy-action.yml
    with:
      input-1: ${{ inputs.use-input && inputs.string-input || 'DUCK' }}
